server:
  port: 8082

spring:
  profiles:
    active: dev,release
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.14.217:13306/note
    username: root
    password: mysqlondocker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update